//
// Created by moram on 2016/11/25.
//
#include <jni.h>
#include "android/log.h"
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR,"NDK_demo",__VA_ARGS__)

/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class com_szh_ndkdemo_MainActivity */
#ifndef _Included_com_szh_ndkdemo_MainActivity
#define _Included_com_szh_ndkdemo_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_szh_ndkdemo_MainActivity
 * Method:    addTest
 * Signature: (II)I；参数和返回值
 */
JNIEXPORT jint JNICALL Java_com_szh_ndkdemo_MainActivity_addTest
  (JNIEnv *evn,jobject jclass,jint a,jint b){
    int sum=a+b;
    LOGE("ndk_go");
    return sum;
  }

#ifdef __cplusplus
}
#endif
#endif